### ISSUE TITLE
TODO refractor

### ISSUE THREAD

**Issue by OptimusCrime** [OptimusCrime/youkok2#133]
Views
- [x] Frontpage
- [x] Download
- [x] Redirect
- [x] Register
- [x] Flat pages
- [x] 404
- [x] Database error
- [x] User stuff
- [x] Archives

Functionality
- [ ] All models + controllers
- [x] Processors in own directory
- [x] Remove typeahead file

Layout
- [x] Mobile first
- [x] Fix mobile views

Other stuff
- [ ] Search is fucked
- [ ] Mail @ download error

Tests
- [ ] Test everything
