### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by OptimusCrime** [OptimusCrime/youkok2#241]
1. Fix the search. 100%
2. Fix the graybox processors to work again
3. Fix the update user preferences system + processors 
4. Fix uploading and submitting links
5. Implement caching system redis.

## Phase 1

- [x] Fix the archive, so it renders
- [ ] Make it possible to upload files and post links
- [ ] Fix the graybox processors
- [x] Fix the frontpage

## Phase 2

- [x] Fix the search
- [ ] Implement admin interface that can handle moderation

(Upgrade?)

## Phase 3

- [ ] Rewrite the js
- [ ] Fix the tasks and jobs
